// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by scripts/generate-assets.js

export const assetManifest = [
  "src/assets/characters/cat-idle.png",
  "src/assets/characters/cat-sleep.png",
  "src/assets/characters/cat-walk-1.png",
  "src/assets/characters/cat-walk-2.png",
  "src/assets/characters/cat-walk-3.png",
  "src/assets/characters/cat-walk-4.png",
  "src/assets/dojo/buildings/dojo-lv1.png",
  "src/assets/dojo/buildings/dojo2-lv1.png",
  "src/assets/dojo/objects/bamboo-grove.png",
  "src/assets/dojo/objects/hanging-banner.png",
  "src/assets/dojo/objects/onigiri-stand.png",
  "src/assets/dojo/objects/training-lantern.png",
  "src/assets/dojo/objects/training-yard.png",
  "src/assets/dojo/objects/weapon-rack.png",
  "src/assets/dojo/objects/zen-garden.png",
  "src/assets/nature/bush-1.png",
  "src/assets/nature/sakura-bloom-1.png",
  "src/assets/nature/sakura-bloom-2.png",
  "src/assets/nature/sakura-dying.png",
  "src/assets/nature/sakura-small.png",
  "src/assets/nature/sakura-style1.png",
  "src/assets/park/objects/bamboo-fence.png",
  "src/assets/park/objects/bird-feeding-station.png",
  "src/assets/park/objects/flower-bed.png",
  "src/assets/park/objects/koi-pond.png",
  "src/assets/park/objects/paper-lantern-post.png",
  "src/assets/park/objects/red-torii-gate.png",
  "src/assets/park/objects/stone-lantern.png",
  "src/assets/park/objects/vending-machine.png",
  "src/assets/park/objects/wooden-bench.png",
  "src/assets/park/tiles/grass-tile.png",
  "src/assets/park/tiles/stone-path-corner.png",
  "src/assets/park/tiles/stone-path-straight.png",
  "src/assets/park/tiles/stone-path-tjunction.png",
  "src/assets/shared/effects/level-up-effect.png",
  "src/assets/shared/effects/xp-orb.png",
  "src/assets/shared/objects/mailbox.png",
  "src/assets/shared/objects/street-lamp.png",
  "src/assets/shared/objects/woodcrate.png",
  "src/assets/shared/objects/wooden-bridge.png",
  "src/assets/study/objects/bonsai.png",
  "src/assets/study/objects/bookshelf.png",
  "src/assets/study/objects/incense-holder.png",
  "src/assets/study/objects/paper-lantern.png",
  "src/assets/study/objects/piano.png",
  "src/assets/study/objects/study-desk.png",
  "src/assets/study/objects/zabuton.png",
  "src/assets/teahouse/buildings/teahouse-main.png",
  "src/assets/teahouse/objects/outdoor-terrace.png",
  "src/assets/teahouse/objects/serving-cart (1).png",
  "src/assets/teahouse/objects/stepping-stones.png",
  "src/assets/teahouse/objects/tea-counter.png",
  "src/assets/teahouse/objects/tea-table.png",
  "src/assets/teahouse/objects/water-basin.png",
  "src/assets/teahouse/objects/wind-chime.png",
  "src/assets/teahouse/objects/wisteria-trellis.png",
  "src/assets/tiles/spritesheet.png",
  "src/assets/tiles/tile_000.png",
  "src/assets/tiles/tile_001.png",
  "src/assets/tiles/tile_002.png",
  "src/assets/tiles/tile_003.png",
  "src/assets/tiles/tile_004.png",
  "src/assets/tiles/tile_005.png",
  "src/assets/tiles/tile_006.png",
  "src/assets/tiles/tile_007.png",
  "src/assets/tiles/tile_008.png",
  "src/assets/tiles/tile_009.png",
  "src/assets/tiles/tile_010.png",
  "src/assets/tiles/tile_011.png",
  "src/assets/tiles/tile_012.png",
  "src/assets/tiles/tile_013.png",
  "src/assets/tiles/tile_014.png",
  "src/assets/tiles/tile_015.png",
  "src/assets/tiles/tile_016.png",
  "src/assets/tiles/tile_017.png",
  "src/assets/tiles/tile_018.png",
  "src/assets/tiles/tile_019.png",
  "src/assets/tiles/tile_020.png",
  "src/assets/tiles/tile_021.png",
  "src/assets/tiles/tile_022.png",
  "src/assets/tiles/tile_023.png",
  "src/assets/tiles/tile_024.png",
  "src/assets/tiles/tile_025.png",
  "src/assets/tiles/tile_026.png",
  "src/assets/tiles/tile_027.png",
  "src/assets/tiles/tile_028.png",
  "src/assets/tiles/tile_029.png",
  "src/assets/tiles/tile_030.png",
  "src/assets/tiles/tile_031.png",
  "src/assets/tiles/tile_032.png",
  "src/assets/tiles/tile_033.png",
  "src/assets/tiles/tile_034.png",
  "src/assets/tiles/tile_035.png",
  "src/assets/tiles/tile_036.png",
  "src/assets/tiles/tile_037.png",
  "src/assets/tiles/tile_038.png",
  "src/assets/tiles/tile_039.png",
  "src/assets/tiles/tile_040.png",
  "src/assets/tiles/tile_041.png",
  "src/assets/tiles/tile_042.png",
  "src/assets/tiles/tile_043.png",
  "src/assets/tiles/tile_044.png",
  "src/assets/tiles/tile_045.png",
  "src/assets/tiles/tile_046.png",
  "src/assets/tiles/tile_047.png",
  "src/assets/tiles/tile_048.png",
  "src/assets/tiles/tile_049.png",
  "src/assets/tiles/tile_050.png",
  "src/assets/tiles/tile_051.png",
  "src/assets/tiles/tile_052.png",
  "src/assets/tiles/tile_053.png",
  "src/assets/tiles/tile_054.png",
  "src/assets/tiles/tile_055.png",
  "src/assets/tiles/tile_056.png",
  "src/assets/tiles/tile_057.png",
  "src/assets/tiles/tile_058.png",
  "src/assets/tiles/tile_059.png",
  "src/assets/tiles/tile_060.png",
  "src/assets/tiles/tile_061.png",
  "src/assets/tiles/tile_062.png",
  "src/assets/tiles/tile_063.png",
  "src/assets/tiles/tile_064.png",
  "src/assets/tiles/tile_065.png",
  "src/assets/tiles/tile_066.png",
  "src/assets/tiles/tile_067.png",
  "src/assets/tiles/tile_068.png",
  "src/assets/tiles/tile_069.png",
  "src/assets/tiles/tile_070.png",
  "src/assets/tiles/tile_071.png",
  "src/assets/tiles/tile_072.png",
  "src/assets/tiles/tile_073.png",
  "src/assets/tiles/tile_074.png",
  "src/assets/tiles/tile_075.png",
  "src/assets/tiles/tile_076.png",
  "src/assets/tiles/tile_077.png",
  "src/assets/tiles/tile_078.png",
  "src/assets/tiles/tile_079.png",
  "src/assets/tiles/tile_080.png",
  "src/assets/tiles/tile_081.png",
  "src/assets/tiles/tile_082.png",
  "src/assets/tiles/tile_083.png",
  "src/assets/tiles/tile_084.png",
  "src/assets/tiles/tile_085.png",
  "src/assets/tiles/tile_086.png",
  "src/assets/tiles/tile_087.png",
  "src/assets/tiles/tile_088.png",
  "src/assets/tiles/tile_089.png",
  "src/assets/tiles/tile_090.png",
  "src/assets/tiles/tile_091.png",
  "src/assets/tiles/tile_092.png",
  "src/assets/tiles/tile_093.png",
  "src/assets/tiles/tile_094.png",
  "src/assets/tiles/tile_095.png",
  "src/assets/tiles/tile_096.png",
  "src/assets/tiles/tile_097.png",
  "src/assets/tiles/tile_098.png",
  "src/assets/tiles/tile_099.png",
  "src/assets/tiles/tile_100.png",
  "src/assets/tiles/tile_101.png",
  "src/assets/tiles/tile_102.png",
  "src/assets/tiles/tile_103.png",
  "src/assets/tiles/tile_104.png",
  "src/assets/tiles/tile_105.png",
  "src/assets/tiles/tile_106.png",
  "src/assets/tiles/tile_107.png",
  "src/assets/tiles/tile_108.png",
  "src/assets/tiles/tile_109.png",
  "src/assets/tiles/tile_110.png",
  "src/assets/tiles/tile_111.png",
  "src/assets/tiles/tile_112.png",
  "src/assets/tiles/tile_113.png",
  "src/assets/tiles/tile_114.png"
];

export function preloadAssets(scene) {
  // Validate manifest exists
  if (!assetManifest || assetManifest.length === 0) {
    console.error('❌ [preloadAssets] Asset manifest is empty or missing. Run: npm run generate-assets')
    return
  }

  console.group('📦 [preloadAssets]')
  console.log(`Loading ${assetManifest.length} assets from manifest`)

  // Keep filenames as-is for cleaner keys that match the asset library
  // E.g.: "red-torii-gate", "dojo-lv1", "sakura-bloom-1", "tile_037"
  const toKey = (assetPath) => {
    const fileName = assetPath.split('/').pop().replace('.png', '')
    return fileName
  }

  let loadedCount = 0
  const failedAssets = []

  assetManifest.forEach(assetPath => {
    const key = toKey(assetPath)
    try {
      scene.load.image(key, assetPath)
      loadedCount++
    } catch (e) {
      failedAssets.push({ key, path: assetPath, error: e.message })
    }
  })

  console.log(`✅ Queued ${loadedCount} assets`)
  if (failedAssets.length > 0) {
    console.warn(`⚠️  ${failedAssets.length} assets failed to queue:`)
    failedAssets.forEach(({ key, error }) => {
      console.warn(`   - ${key}: ${error}`)
    })
  }
  console.groupEnd()
}
