#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..')

// we no longer need an explicit list of asset directories; scanAssets
// walks the entire `src/assets` tree recursively.

function scanAssets() {
  // Recursively walk `public/assets` and return flat array of png paths
  // (relative to public/ so they resolve correctly in both dev and production)
  const assets = []
  const publicDir = path.join(projectRoot, 'public')
  const baseDir = path.join(publicDir, 'assets')

  function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    entries.forEach(entry => {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(fullPath)
      } else if (entry.isFile() && entry.name.endsWith('.png')) {
        // compute path relative to public/ so URL = /assets/... in both dev + prod
        const relPath = path.relative(publicDir, fullPath).split(path.sep).join('/')
        assets.push(relPath)
      }
    })
  }

  if (fs.existsSync(baseDir)) {
    walk(baseDir)
  }

  return assets
}

function generatePreloadCode(assets) {
  let code = `// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by scripts/generate-assets.js

export const assetManifest = ${JSON.stringify(assets, null, 2)};

export function preloadAssets(scene) {
  // Keep filenames as-is for cleaner keys that match the asset library
  // E.g.: "red-torii-gate", "dojo-lv1", "sakura-bloom-1", "tile_037"
  const toKey = (assetPath) => {
    const fileName = assetPath.split('/').pop().replace('.png', '')
    return fileName
  }

  assetManifest.forEach(assetPath => {
    const key = toKey(assetPath)
    scene.load.image(key, assetPath)
  })
}
`

  return code
}

function main() {
  console.log('🔍 Scanning assets...')
  const assets = scanAssets()

  console.log('📝 Generating preload code...')
  const code = generatePreloadCode(assets)

  const outputPath = path.join(projectRoot, 'src', 'game', 'preloadAssets.js')
  fs.writeFileSync(outputPath, code)

  console.log(`✅ Asset manifest generated at: ${outputPath}`)
  console.log(`📊 Found ${assets.length} asset${assets.length === 1 ? '' : 's'}`)
}

main()